;;; config-tests.el --- Behavioral checks for editor workflows -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)

(defmacro my/test-typescript (text &rest body)
  (declare (indent 1))
  `(with-temp-buffer
     (insert ,text)
     (treesit-parser-create 'typescript)
     (goto-char (point-min))
     ,@body))

(ert-deftest my/structure-function-and-argument-objects ()
  (my/test-typescript "function example(a: string, b: number) {\n  return call(a, b);\n}\n"
		      (search-forward "return")
		      (let ((bounds (evil-textobj-plus-find ?f nil 1 'cover)))
			(should (string-prefix-p "function example" (buffer-substring (car bounds) (cdr bounds)))))
		      (let ((bounds (evil-textobj-plus-find ?f t 1 'cover)))
			(should (equal (string-trim (buffer-substring (car bounds) (cdr bounds))) "return call(a, b);")))
		      (search-forward "call(a")
		      (backward-char)
		      (let ((bounds (evil-textobj-plus-find ?a nil 1 'cover)))
			(should (equal (buffer-substring (car bounds) (cdr bounds)) "a, ")))
		      (search-forward "b")
		      (backward-char)
		      (let ((bounds (evil-textobj-plus-find ?a nil 1 'cover)))
			(should (equal (buffer-substring (car bounds) (cdr bounds)) ", b")))))

(ert-deftest my/textobj-plus-preserves-function-and-call-mappings ()
  (my/test-typescript "function outer(a: string, b: number) { return call(a, b); }"
    (save-window-excursion
      (switch-to-buffer (current-buffer))
      (evil-local-mode 1) (evil-normal-state)
      (search-forward "return")
      (execute-kbd-macro (kbd "vaf"))
      (should (string-prefix-p "function outer"
                               (buffer-substring evil-visual-beginning evil-visual-end)))
      (evil-normal-state)
      (goto-char (point-min)) (search-forward "call(a") (backward-char)
      (execute-kbd-macro (kbd "viF"))
      (should (equal (buffer-substring evil-visual-beginning evil-visual-end) "a, b")))))

(ert-deftest my/textobj-plus-nearby-operators-without-parser ()
  (should (= evil-textobj-plus-lines 500))
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "before (one) after (two)")
    (save-window-excursion
      (switch-to-buffer (current-buffer))
      (goto-char (point-min)) (evil-local-mode 1) (evil-normal-state)
      (execute-kbd-macro (kbd "di)"))
      (should (equal (buffer-string) "before () after (two)"))
      (execute-kbd-macro (kbd "din)"))
      (should (equal (buffer-string) "before () after ()")))))

(ert-deftest my/structure-nested-functions-and-folds ()
  (my/test-typescript "function outer() {\n const inner = () => {\n return 1;\n };\n}\nfunction last() {}"
		      (let ((positions (my/treesit-function-positions (treesit-buffer-root-node)) ))
			(should (= 3 (length positions))))
		      (my/next-function 1)
		      (should (looking-at "() =>"))
		      (my/previous-function 1)
		      (should (= (point-min) (point)))
		      (search-forward "return")
		      (my/toggle-fold)
		      (should (seq-some (lambda (o) (overlay-get o 'my/structural-fold))
					(overlays-in (point-min) (point-max))))
		      (my/toggle-fold)
		      (should-not (overlays-in (point-min) (point-max)))))

(ert-deftest my/structure-without-parser-explains-requirement ()
  (with-temp-buffer (should-error (evil-textobj-plus-find ?f t 1 'cover) :type 'user-error)))

(ert-deftest my/keybindings-preserve-navigation-and-share-cursor-engine ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (evil-local-mode 1)
    (evil-normal-state)
    (evil-normalize-keymaps)
    (dolist (pair '(("SPC SPC" . project-find-file)
                    ("SPC ," . consult-project-buffer)
                    ("SPC e" . my/project-explorer)
                    ("SPC t r" . my/project-test-nearest)
                    ("SPC m n" . evil-mc-make-and-goto-next-match)
                    ("gr" . my/lsp-find-references)
                    ("gI" . my/lsp-find-implementations)
                    ("C-h" . windmove-left)))
      (should (eq (key-binding (kbd (car pair))) (cdr pair))))))

(ert-deftest my/format-now-does-not-enable-save-formatting ()
  (require 'apheleia)
  (with-temp-buffer
    (let ((apheleia-mode nil) seen)
      (cl-letf (((symbol-function 'my/project-formatter) #'ignore)
                ((symbol-function 'apheleia--get-formatters) (lambda (&rest _) '(prettier)))
                ((symbol-function 'apheleia-format-buffer) (lambda (formatters &rest _) (setq seen formatters))))
        (my/format-buffer)
        (should (equal seen '(prettier)))
        (should-not apheleia-mode)))))

(defvar lsp-managed-mode)
(defvar lsp-mode)

(ert-deftest my/definition-prefers-attached-lsp-and-falls-back-to-xref ()
  ;; lsp-mode may be on while the server is still starting; only a managed
  ;; buffer is attached and ready for LSP navigation.
  (dolist (state '((t t lsp) (nil nil xref) (t nil xref)))
    (let ((lsp-mode (nth 0 state))
          (lsp-managed-mode (nth 1 state))
          called)
      (cl-letf (((symbol-function 'lsp-find-definition)
                 (lambda () (interactive) (setq called 'lsp)))
                ((symbol-function 'xref-find-definitions)
                 (lambda () (interactive) (setq called 'xref))))
        (my/lsp-find-definitions)
        (should (eq called (nth 2 state)))))))

(ert-deftest my/task-discovery-quotes-script-names ()
  (let ((directory (make-temp-file "emacs-task-" t)))
    (unwind-protect
        (progn
          (with-temp-file (expand-file-name "package.json" directory)
            (insert "{\"scripts\":{\"test:unit\":\"vitest\",\"odd name\":\"true\"}}"))
          (with-temp-file (expand-file-name "pnpm-lock.yaml" directory))
          (should (equal (cdr (assoc "script: odd name" (my/task-choices directory)))
                         (concat "pnpm run " (shell-quote-argument "odd name")))))
      (delete-directory directory t))))

(ert-deftest my/task-history-is-project-specific ()
  (let ((my/project-last-tasks '(("/tmp/one/" . "first") ("/tmp/two/" . "second"))) captured)
    (cl-letf (((symbol-function 'my/task-root) (lambda () "/tmp/two/"))
              ((symbol-function 'my/task-run) (lambda (root command) (setq captured (list root command)))))
      (my/project-rerun-task)
      (should (equal captured '("/tmp/two/" "second"))))))

(ert-deftest my/task-nearest-js-test-uses-enclosing-call ()
  (my/test-typescript "describe('group', () => { it('adds numbers', () => { expect(1).toBe(1); }); });"
		      (search-forward "expect")
		      (should (equal (my/task-nearest-js-test) "group adds numbers"))))

(ert-deftest my/task-pytest-class-selector ()
  (let ((root (file-name-as-directory (make-temp-file "lazyemacs-pytest-" t))))
    (unwind-protect
        (with-temp-buffer
          (python-mode)
          (setq buffer-file-name (expand-file-name "test_api.py" root))
          (insert "class TestAPI:\n    def test_ok(self):\n        assert True\n")
          (search-backward "assert")
          (should (equal (my/task-test-command root t)
                         (concat "python -m pytest " (shell-quote-argument "test_api.py::TestAPI::test_ok")))))
      (delete-directory root t))))

(ert-deftest my/session-filter-preserves-projects-not-runtime-objects ()
  (let* ((tabs `(tabs (tab (name . "review") (group . "Project")
                           (project-tab-sessions-root . "/tmp/project/")
                           (my/ghostel-buffer . ,(current-buffer))
                           (my/zoom-state . ,(current-window-configuration)))))
         (filtered (frameset-filter-tabs tabs nil nil t))
         (tab (cadr filtered)))
    (should (equal (alist-get 'project-tab-sessions-root tab) "/tmp/project/"))
    (should (equal (alist-get 'group tab) "Project"))
    (should-not (assq 'my/ghostel-buffer tab))
    (should-not (assq 'my/zoom-state tab))
    (should (assq 'my/ghostel-buffer (cadr tabs)))
    (should (equal filtered (read (prin1-to-string filtered))))))

(ert-deftest my/session-zoom-roundtrip ()
  (save-window-excursion
    (delete-other-windows)
    (split-window-right)
    (let ((count (length (window-list))))
      (my/window-zoom)
      (should (= 1 (length (window-list))))
      (my/window-zoom)
      (should (= count (length (window-list)))))))

(ert-deftest my/session-terminal-restore-does-not-start-a-process ()
  (let ((buffer (my/session-restore-terminal nil "*test-saved-terminal*" "/tmp/")))
    (unwind-protect
        (with-current-buffer buffer
          (should (eq major-mode 'my/session-terminal-mode))
          (should (equal default-directory "/tmp/"))
          (should-not (get-buffer-process buffer))
          (should (eq (key-binding (kbd "RET")) #'my/session-terminal-open)))
      (kill-buffer buffer))))

(ert-deftest my/task-js-regexp-is-literal ()
  (should (equal (my/task-js-test-regexp "group adds (1+2)?")
                 "^group adds \\(1\\+2\\)\\?$")))

(ert-deftest my/session-desktop-roundtrip ()
  (let* ((directory (make-temp-file "emacs-desktop-test-" t))
         (file (expand-file-name "fixture.txt" directory))
         (desktop-dirname directory)
         (desktop-path (list directory))
         (desktop-load-locked-desktop t)
         (desktop-restore-eager t)
         (desktop-restore-frames t)
         (tab-bar-new-tab-choice nil)
         (old-tabs (frame-parameter nil 'tabs)))
    (unwind-protect
        (save-window-excursion
          (with-temp-file file (insert "first\nsecond\nthird\n"))
          (switch-to-buffer (find-file-noselect file))
          (goto-char 8)
          (tab-bar-rename-tab "implementation")
          (tab-bar-change-tab-group "fixture-project")
          (setf (alist-get 'project-tab-sessions-root
                           (cdr (tab-bar--current-tab-find))) directory)
          (tab-bar-new-tab)
          (tab-bar-rename-tab "review")
          (split-window-right)
          (desktop-save directory t)
          (let ((saved (with-temp-buffer
                         (insert-file-contents (expand-file-name desktop-base-file-name directory))
                         (buffer-string))))
            (should-not (string-match-p "#<" saved)))
          (delete-other-windows)
          (tab-bar-close-other-tabs)
          (tab-bar-rename-tab "changed")
          (let ((noninteractive nil) (my/session-directory directory))
            (my/session-restore))
          (should (= 2 (length (funcall tab-bar-tabs-function))))
          (should (equal "review" (alist-get 'name (tab-bar--current-tab-find))))
          (should (equal "fixture-project" (alist-get 'group (tab-bar--current-tab-find))))
          (should (= 2 (length (window-list))))
          (tab-bar-select-tab 1)
          (should (equal directory (alist-get 'project-tab-sessions-root
                                              (tab-bar--current-tab-find))))
          (should (= 8 (point))))
      (set-frame-parameter nil 'tabs old-tabs)
      (when-let* ((buffer (get-file-buffer file))) (kill-buffer buffer))
      (delete-directory directory t))))

(ert-deftest my/flash-bindings ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (evil-local-mode 1)
    (dolist (state '(normal visual motion operator))
      (evil-change-state state)
      (evil-normalize-keymaps)
      (dolist (pair '(("s" . flash-evil-jump) ("S" . flash-treesitter)
                      ("f" . flash-char-find) ("t" . flash-char-find-to)
                      ("F" . flash-char-find-backward) ("T" . flash-char-find-to-backward)
                      (";" . flash-char-repeat) ("," . flash-char-repeat-reverse)))
        (should (eq (key-binding (kbd (car pair))) (if (and (eq state 'operator) (equal (car pair) "S")) 'my/flash-treesitter-object (cdr pair))))))))
(ert-deftest my/flash-operator-and-selection ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (insert "abcxdef")
      (evil-local-mode 1)
      (evil-normal-state)
      (goto-char 1)
      (execute-kbd-macro (kbd "d f x"))
      (should (equal (buffer-string) "def"))
      (erase-buffer)
      (insert "function example(a: string) { return a; }\n")
      (treesit-parser-create 'typescript)
      (goto-char 10)
      (execute-kbd-macro (kbd "S RET"))
      (should (evil-visual-state-p))
      (should (equal (buffer-substring evil-visual-beginning evil-visual-end) "example"))
      (evil-normal-state)
      (goto-char 10)
      (execute-kbd-macro (kbd "d S RET"))
      (should (equal (buffer-string) "function (a: string) { return a; }\n")))))

(ert-deftest my/popup-first-display-and-reopen-use-evil ()
  (let ((buffer (generate-new-buffer "*Warnings*<evil-popup-test>"))
        (popper-group-function nil)
        (popper-open-popup-alist nil)
        (popper-buried-popup-alist nil))
    (unwind-protect
        (save-window-excursion
          (with-current-buffer buffer
            (insert "alpha beta\nsecond line\nthird line\n")
            (special-mode)
            (evil-local-mode 1)
            (evil-emacs-state))
          ;; Exercise the real display-buffer rule, not just the hook helper.
          (let ((window (display-buffer buffer)))
            (should (window-live-p window))
            (with-selected-window window
              (should (eq evil-state 'normal))
              (goto-char (point-min))
              (execute-kbd-macro (kbd "w j"))
              (should (= (line-number-at-pos) 2))
              (should (eq (key-binding (kbd "C-h")) #'windmove-left))))
          (popper--update-popups)
          (popper-close-latest)
          (with-current-buffer buffer (evil-emacs-state))
          (popper-open-latest)
          (with-current-buffer buffer
            (should (eq evil-state 'normal))
            (should (eq (key-binding (kbd "w")) #'evil-forward-word-begin))))
      (when (buffer-live-p buffer) (kill-buffer buffer)))))

(ert-deftest my/popup-preserves-interactive-shell-input ()
  (require 'comint)
  (with-temp-buffer
    (comint-mode)
    (evil-local-mode 1)
    (evil-insert-state)
    (my/popper-evil-normal-state)
    (should (eq evil-state 'insert))))

(ert-deftest my/diagnostics-are-explicit-and-do-not-feed-eldoc ()
  (require 'flycheck)
  (with-temp-buffer
    (let* ((flycheck-mode t)
           (error (flycheck-error-new-at 1 1 'error "Example diagnostic"))
           automatic-docs explicit-errors)
      (should-not flycheck-display-errors-function)
      (cl-letf (((symbol-function 'flycheck-overlay-errors-at)
                 (lambda (&rest _) (list error)))
                ((symbol-function 'flycheck-display-error-messages)
                 (lambda (errors) (setq explicit-errors errors))))
        ;; The idle provider must stay silent even with an error at point.
        (flycheck-eldoc-function (lambda (&rest docs) (setq automatic-docs docs)))
        (flycheck-display-error-at-point)
        (should-not automatic-docs)
        (should-not explicit-errors)
        (my/show-diagnostic-at-point)
        (should (equal explicit-errors (list error)))
        (should-not flycheck-display-errors-function)))))

(setq kill-emacs-hook nil)
(ert-run-tests-batch-and-exit)
