;;; lazyvim-keymap-tests.el --- Keymap migration behavior -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'flycheck)
(require 'lsp-mode)
(require 'ghostel)

(ert-deftest my/lazyvim-editing-keys-and-preserved-window-navigation ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (evil-local-mode 1)
    (evil-normal-state)
    (dolist (pair '(("H" . previous-buffer) ("L" . next-buffer)
                    ("gi" . evil-insert-resume) ("gI" . my/lsp-find-implementations)
                    ("SPC f t" . my/project-ghostel) ("SPC f T" . my/directory-ghostel)
                    ("SPC f p" . project-switch-project) ("SPC c d" . my/show-diagnostic-at-point)
                    ("SPC c R" . crux-rename-file-and-buffer) ("SPC g s" . magit-status)
                    ("SPC g h s" . diff-hl-stage-current-hunk)
                    ("SPC t l" . my/project-test-last) ("SPC TAB d" . tab-bar-close-tab)
                    ("SPC <tab> <tab>" . tab-bar-new-tab)
                    ("SPC s r" . my/search-replace) ("SPC u f" . my/toggle-global-format-on-save)
                    ("SPC u F" . my/toggle-format-on-save)))
      (should (eq (key-binding (kbd (car pair))) (cdr pair)))))
  (dolist (state '(normal insert visual motion emacs replace))
    (with-temp-buffer
      (emacs-lisp-mode)
      (evil-local-mode 1)
      (evil-change-state state)
      (dolist (pair '(("C-h" . windmove-left) ("C-j" . windmove-down)
                      ("C-k" . windmove-up) ("C-l" . windmove-right)))
        (should (eq (key-binding (kbd (car pair))) (cdr pair)))))))

(ert-deftest my/lazyvim-save-and-move-are-editing-only ()
  (dolist (state '(normal insert visual replace))
    (with-temp-buffer
      (text-mode)
      (evil-local-mode 1)
      (evil-change-state state)
      (should (eq (key-binding (kbd "C-s")) #'save-buffer))
      (should (eq (key-binding (kbd "M-j")) #'move-text-down))
      (should (eq (key-binding (kbd "M-k")) #'move-text-up))))
  (with-temp-buffer
    (special-mode)
    (should-not my/editor-shortcuts-mode)
    (setq major-mode 'ghostel-mode)
    (my/editor-shortcuts-setup)
    (should-not my/editor-shortcuts-mode))
  (dolist (map (list ghostel-mode-map ghostel-char-mode-map ghostel-semi-char-mode-map))
    (should (eq (lookup-key map (kbd "C-h")) #'windmove-left))
    (should (eq (lookup-key map (kbd "C-k")) #'windmove-up))
    (should (eq (lookup-key map (kbd "C-/")) #'my/ghostel-toggle))))

(ert-deftest my/lazyvim-terminal-reuse-fresh-cwd-and-hide ()
  (let ((tab '(current-tab (name . "test") (group . "Test")))
        (default-directory temporary-file-directory)
        created shown hidden)
    (unwind-protect
        (cl-letf (((symbol-function 'tab-bar--current-tab-find) (lambda (&rest _) tab))
                  ((symbol-function 'project-current) (lambda (&rest _) nil))
                  ((symbol-function 'ghostel-create)
                   (lambda (&rest _)
                     (let ((buffer (generate-new-buffer " *fake-terminal*")))
                       (push buffer created) buffer)))
                  ((symbol-function 'pop-to-buffer) (lambda (buffer &rest _) (setq shown buffer)))
                  ((symbol-function 'get-buffer-window) (lambda (&rest _) nil)))
          (let ((first (my/project-ghostel)))
            (my/ghostel-toggle)
            (should (eq first shown))
            (should (= 1 (length created)))
            (should-not (eq first (my/project-ghostel '(4))))
            (let ((project-terminal (alist-get 'my/ghostel-buffer tab))
                  (cwd-terminal (my/directory-ghostel)))
              (should-not (eq cwd-terminal project-terminal))
              (should (eq cwd-terminal (my/directory-ghostel)))
              (should (eq project-terminal (my/project-ghostel)))
              (cl-letf (((symbol-function 'get-buffer-window) (lambda (&rest _) 'pane))
                        ((symbol-function 'quit-window) (lambda (&rest _) (setq hidden t))))
                (my/ghostel-toggle)
                (should hidden)
                (should (buffer-live-p project-terminal))))))
      (mapc #'kill-buffer created))))

(ert-deftest my/lazyvim-range-formatting-never-formats-whole-buffer ()
  (with-temp-buffer
    (insert "before\nselected\nafter\n")
    (let ((lsp-managed-mode t) seen)
      (cl-letf (((symbol-function 'lsp-feature?) (lambda (_) t))
                ((symbol-function 'lsp-format-region) (lambda (beg end) (setq seen (list beg end))))
                ((symbol-function 'apheleia-format-buffer) (lambda (&rest _) (ert-fail "Whole-buffer format"))))
        (my/format-buffer 8 16)
        (should (equal seen '(8 16))))
      (cl-letf (((symbol-function 'lsp-feature?) (lambda (_) nil)))
        (should-error (my/format-buffer 8 16) :type 'user-error)))))

(ert-deftest my/lazyvim-diagnostics-filter-exact-severity-and-count ()
  (with-temp-buffer
    (insert "a\nb\nc\nd\ne\n")
    (setq-local flycheck-current-errors
                (list (flycheck-error-new-at 2 1 'warning "warn")
                      (flycheck-error-new-at 3 1 'error "error")
                      (flycheck-error-new-at 4 1 'warning "warn")))
    (cl-letf (((symbol-function 'flycheck-display-error-at-point) #'ignore))
      (goto-char (point-min))
      (my/next-warning-diagnostic 2)
      (should (= 4 (line-number-at-pos)))
      (my/previous-error-diagnostic 1)
      (should (= 3 (line-number-at-pos)))
      (should-error (my/next-error-diagnostic 1) :type 'user-error))))

(ert-deftest my/lazyvim-call-hierarchy-uses-target-locations ()
  (dolist (outgoing '(nil t))
    (let* ((item '(:name "caller" :uri "file:///tmp/a" :selectionRange (:start (:line 0 :character 0) :end (:line 0 :character 1))))
           (target '(:name "target" :uri "file:///tmp/b" :selectionRange (:start (:line 2 :character 0) :end (:line 2 :character 1))))
           requests locations shown)
      (cl-letf (((symbol-function 'my/lsp-require-feature)
                 (lambda (method) (should (assoc method lsp-method-requirements))))
                ((symbol-function 'lsp--text-document-position-params) (lambda () 'position))
                ((symbol-function 'lsp-request)
                 (lambda (method params)
                   (push (cons method params) requests)
                   (if (equal method "textDocument/prepareCallHierarchy")
                       (vector item) (vector (list (if outgoing :to :from) target)))))
                ((symbol-function 'lsp--locations-to-xref-items)
                 (lambda (value) (setq locations value) '(xref)))
                ((symbol-function 'xref-show-xrefs)
                 (lambda (fetcher _) (setq shown (funcall fetcher)))))
        (my/lsp-call-hierarchy outgoing)
        (should (equal shown '(xref)))
        (should (equal (plist-get (car locations) :uri) "file:///tmp/b"))
        (should (equal (caar requests) (if outgoing "callHierarchy/outgoingCalls" "callHierarchy/incomingCalls")))))))

(ert-deftest my/lazyvim-test-history-and-output-independent-of-tasks ()
  (let ((my/project-last-tasks nil) (my/project-last-tests nil)
        (my/project-task-buffers (make-hash-table :test #'equal))
        (my/project-test-buffers (make-hash-table :test #'equal))
        (root (file-name-as-directory temporary-file-directory)) buffers)
    (unwind-protect
        (cl-letf (((symbol-function 'save-some-buffers) #'ignore)
                  ((symbol-function 'compilation-start)
                   (lambda (_command _mode name)
                     (let ((buffer (get-buffer-create (funcall name nil))))
                       (cl-pushnew buffer buffers) buffer)))
                  ((symbol-function 'my/task-root) (lambda () root)))
          (my/task-run root "test-file" t)
          (let ((test-buffer (gethash root my/project-test-buffers)))
            (my/task-run root "build")
            (my/project-test-last)
            (should (equal (alist-get root my/project-last-tests nil nil #'equal) "test-file"))
            (should (equal (alist-get root my/project-last-tasks nil nil #'equal) "build"))
            (should (eq test-buffer (gethash root my/project-test-buffers)))
            (should-not (eq test-buffer (gethash root my/project-task-buffers)))))
      (mapc #'kill-buffer buffers))))

(ert-deftest my/lazyvim-close-other-tabs-is-session-scoped ()
  (tab-bar-change-tab-group "Keep")
  (tab-bar-new-tab)
  (tab-bar-change-tab-group "Other")
  (tab-bar-new-tab)
  (tab-bar-change-tab-group "Keep")
  (my/session-close-other-tabs)
  (should (= 1 (length (project-tab-sessions--tabs "Keep"))))
  (should (= 1 (length (project-tab-sessions--tabs "Other"))))
  (my/session-first-tab)
  (my/session-last-tab)
  (should (equal (alist-get 'group (tab-bar--current-tab-find)) "Keep")))

(ert-deftest my/lazyvim-git-copy-does-not-open-browser ()
  (require 'git-link)
  (let (seen)
    (cl-letf (((symbol-function 'git-link)
               (lambda () (interactive) (setq seen git-link-open-in-browser))))
      (my/git-copy-link) (should-not seen)
      (my/git-browse) (should seen))))

(ert-deftest my/lazyvim-no-missing-leader-commands ()
  (dolist (map (list my/leader-buffer-map my/leader-code-map my/leader-error-map
                     my/leader-file-map my/leader-git-map my/leader-search-map
                     my/leader-test-map my/leader-ui-map my/leader-workspace-map))
    (cl-labels ((check (map)
                  (map-keymap (lambda (_key command)
                                (cond ((keymapp command) (check command))
                                      ((symbolp command) (should (commandp command))))) map)))
      (check map))))

(setq kill-emacs-hook nil)
(ert-run-tests-batch-and-exit "my/lazyvim-")
