;;; reliability-tests.el --- Distribution workflow regressions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'lsp-mode)
(require 'apheleia)

(defvar lazyemacs-test-executed nil)

(ert-deftest lazyemacs/json-parsing-never-evaluates-lisp ()
  (let ((lazyemacs-test-executed nil))
    (with-temp-buffer
      (insert (prin1-to-string (byte-compile '(lambda () (setq lazyemacs-test-executed t)))))
      (goto-char (point-min))
      (should-error (json-parse-buffer))
      (should-not lazyemacs-test-executed)))
  (with-temp-buffer
    (insert "{\"answer\":42}")
    (goto-char (point-min))
    (should (equal (json-parse-buffer :object-type 'plist) '(:answer 42)))))

(ert-deftest lazyemacs/booster-buffers-json-and-preserves-command ()
  (let ((my/lsp-booster-enabled t)
        (command (list "server" "--stdio")))
    (cl-letf (((symbol-function 'executable-find)
               (lambda (name &rest _) (concat "/tools/" name))))
      (should (equal (my/lsp-booster--resolve-command (lambda (&rest _) command) command)
                     '("/tools/emacs-lsp-booster" "--disable-bytecode" "--" "/tools/server" "--stdio")))
      (should (equal command '("server" "--stdio")))
      (should (eq (my/lsp-booster--resolve-command (lambda (&rest _) command) command t) command))
      (let ((default-directory "/ssh:example.invalid:/project/"))
        (should (eq (my/lsp-booster--resolve-command (lambda (&rest _) command) command) command))))))

(ert-deftest lazyemacs/booster-is-optional ()
  (cl-letf (((symbol-function 'executable-find) (lambda (&rest _) nil)))
    (should (equal (my/lsp-booster--resolve-command (lambda (&rest _) '("server")) '("server"))
                   '("server"))))
  (let ((my/lsp-booster-enabled nil))
    (should (equal (my/lsp-booster--resolve-command (lambda (&rest _) '("server")) '("server"))
                   '("server")))))

(ert-deftest lazyemacs/typescript-without-grammars-is-editable ()
  (let ((auto-mode-alist (copy-tree auto-mode-alist))
        (major-mode-remap-alist (copy-tree major-mode-remap-alist)))
    (cl-letf (((symbol-function 'treesit-language-available-p) (lambda (&rest _) nil))
              ((symbol-function 'my/lsp-ensure) #'ignore))
      (lazyemacs-refresh-language-modes)
      (dolist (extension '("ts" "mts" "cts" "tsx"))
        (with-temp-buffer
          (setq buffer-file-name (concat "/tmp/lazyemacs-language." extension))
          (insert "const value: number = 1;\n")
          (set-auto-mode)
          (should (eq major-mode 'typescript-mode))
          (font-lock-ensure)
          (should comment-start)
          (should-not (treesit-parser-list)))))))

(ert-deftest lazyemacs/native-typescript-snippet-ancestry-is-consistent ()
  (require 'typescript-ts-mode)
  (let ((parents (derived-mode-all-parents 'typescript-ts-mode)) messages)
    (should (< (cl-position 'typescript-mode parents) (cl-position 'prog-mode parents)))
    (cl-letf (((symbol-function 'my/lsp-ensure) #'ignore)
              ((symbol-function 'message)
               (lambda (format-string &rest args)
                 (when format-string (push (apply #'format-message format-string args) messages)))))
      (with-temp-buffer
        (typescript-ts-mode)
        (yas--get-snippet-tables)))
    (should-not (seq-some (lambda (message) (string-match-p "Inconsistent hierarchy" message)) messages))))

(ert-deftest lazyemacs/tsx-fallback-does-not-use-typescript-parser ()
  (let ((auto-mode-alist (copy-tree auto-mode-alist))
        (major-mode-remap-alist (copy-tree major-mode-remap-alist)))
    (cl-letf (((symbol-function 'treesit-language-available-p)
               (lambda (language &rest _) (eq language 'typescript)))
              ((symbol-function 'my/lsp-ensure) #'ignore))
      (lazyemacs-refresh-language-modes)
      (with-temp-buffer
        (setq buffer-file-name "/tmp/lazyemacs-language.tsx")
        (set-auto-mode)
        (should (eq major-mode 'typescript-mode))
        (should-not (treesit-parser-list))))))

(ert-deftest lazyemacs/language-modes-respect-private-remaps-and-preference ()
  (let ((auto-mode-alist (copy-tree auto-mode-alist))
        (major-mode-remap-alist '((python-mode . private-python-mode)))
        (lazyemacs-prefer-tree-sitter t))
    (cl-letf (((symbol-function 'treesit-language-available-p) (lambda (&rest _) t)))
      (lazyemacs-refresh-language-modes)
      (should (eq (alist-get 'python-mode major-mode-remap-alist) 'private-python-mode))
      (should (eq (alist-get 'js-mode major-mode-remap-alist) 'js-ts-mode))
      (setq lazyemacs-prefer-tree-sitter nil)
      (lazyemacs-refresh-language-modes)
      (should-not (assq 'js-mode major-mode-remap-alist))
      (should (eq (alist-get 'python-mode major-mode-remap-alist) 'private-python-mode)))))

(ert-deftest lazyemacs/references-and-symbols-work-without-lsp ()
  (let (called)
    (cl-letf (((symbol-function 'lsp-find-references) (lambda () (interactive) (setq called 'lsp)))
              ((symbol-function 'xref-find-references) (lambda () (interactive) (setq called 'xref)))
              ((symbol-function 'consult-lsp-file-symbols) (lambda () (interactive) (setq called 'lsp)))
              ((symbol-function 'consult-imenu) (lambda () (interactive) (setq called 'imenu))))
      (dolist (managed '(nil t))
        (let ((lsp-managed-mode managed))
          (my/lsp-find-references)
          (should (eq called (if managed 'lsp 'xref)))
          (my/lsp-file-symbols)
          (should (eq called (if managed 'lsp 'imenu))))))))

(ert-deftest lazyemacs/diagnostics-toggle-requires-an-attached-server ()
  (let ((lsp-managed-mode nil)
        (my/lsp-diagnostics-enabled t))
    (should-error (my/lsp-toggle-diagnostics) :type 'user-error)
    (should my/lsp-diagnostics-enabled)))

(ert-deftest lazyemacs/python-tests-use-project-environment ()
  (let ((root (make-temp-file "lazyemacs-python-" t)))
    (unwind-protect
        (progn
          (cl-letf (((symbol-function 'executable-find) (lambda (_) nil)))
            (should (equal (my/task-python-command root) "python -m pytest")))
          (with-temp-file (expand-file-name "uv.lock" root) (insert "version = 1\n"))
          (cl-letf (((symbol-function 'executable-find) (lambda (_) "/tools/uv")))
            (should (equal (my/task-python-command root) "uv run --frozen --no-sync --no-python-downloads python -m pytest")))
          (make-directory (expand-file-name ".venv/bin" root) t)
          (let ((python (expand-file-name ".venv/bin/python" root)))
            (with-temp-file python (insert "#!/bin/sh\n"))
            (set-file-modes python #o700)
            (should (equal (my/task-python-command root)
                           (concat (shell-quote-argument python) " -m pytest")))))
      (delete-directory root t))))

(ert-deftest lazyemacs/focused-tests-reject-outside-project-files ()
  (with-temp-buffer
    (setq buffer-file-name "/tmp/outside/test_example.py")
    (should-error (my/task-test-command "/tmp/another-project/" nil) :type 'user-error)))

(ert-deftest lazyemacs/session-save-does-not-overwrite-another-owner ()
  (cl-letf (((symbol-function 'desktop-owner) (lambda (&rest _) (1+ (emacs-pid))))
            ((symbol-function 'desktop-save) (lambda (&rest _) (ert-fail "Overwrote locked session"))))
    (should-error (my/session-save) :type 'user-error)))

(ert-deftest lazyemacs/reload-refuses-changing-live-lsp-transport ()
  (cl-letf (((symbol-function 'completing-read) (lambda (&rest _) "init-lsp-booster.el"))
            ((symbol-function 'load-file) (lambda (&rest _) (ert-fail "Changed active LSP transport"))))
    (should-error (my/reload-init-file) :type 'user-error)))

(ert-deftest lazyemacs/formatter-does-not-probe-remote-projects ()
  (with-temp-buffer
    (setq default-directory "/ssh:example.invalid:/project/")
    (cl-letf (((symbol-function 'locate-dominating-file)
               (lambda (&rest _) (ert-fail "Probed remote project"))))
      (my/project-formatter)
      (should-not (local-variable-p 'apheleia-formatter)))))

(ert-deftest lazyemacs/file-search-supports-fdfind ()
  (let (called)
    (cl-letf (((symbol-function 'executable-find) (lambda (name &rest _) (equal name "fdfind")))
              ((symbol-function 'consult-fd) (lambda (&rest _) (interactive) (setq called 'fd)))
              ((symbol-function 'consult-find) (lambda (&rest _) (interactive) (setq called 'find))))
      (my/consult-find)
      (should (eq called 'fd))
      (setq called nil)
      (my/find-file-cwd)
      (should (eq called 'fd)))))

(setq kill-emacs-hook nil)
(ert-run-tests-batch-and-exit "lazyemacs/")
;;; reliability-tests.el ends here
