;;; session-actions-tests.el --- Session picker actions -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)

(ert-deftest my/session-picker-has-embark-actions ()
  (should (eq (keymap-lookup global-map "s-p") #'my/session-switch))
  (should (eq (completion-metadata-get
               (completion-metadata "" #'my/session-completion-table nil)
               'category)
              'lazyemacs-session))
  (should (eq (lookup-key my/embark-session-map "k") #'my/session-close))
  (should (equal (alist-get 'lazyemacs-session embark-keymap-alist)
                 'my/embark-session-map)))

(ert-deftest my/session-picker-creates-and-closes-only-selected-group ()
  (let ((buffer (generate-new-buffer " *session-action-test*")))
    (unwind-protect
        (progn
          (tab-bar-change-tab-group "Keep")
          (my/session-switch "Close")
          (switch-to-buffer buffer)
          (insert "unsaved text")
          (tab-bar-new-tab)
          (tab-bar-change-tab-group "Close")
          (should (= (length (project-tab-sessions--tabs "Close")) 2))
          (my/session-switch "Keep")
          (my/session-close "Close")
          (should-not (project-tab-sessions--tabs "Close"))
          (should (project-tab-sessions--tabs "Keep"))
          (should (buffer-live-p buffer))
          (should (buffer-modified-p buffer))
          (should-not (member "Close" (all-completions "" #'my/session-completion-table)))
          (my/session-switch "Current")
          (my/session-close "Current")
          (should (equal (alist-get 'group (tab-bar--current-tab-find)) "Keep"))
          (should-error (my/session-close "Keep") :type 'user-error)
          (should-error (my/session-close "Missing") :type 'user-error)
          (should (project-tab-sessions--tabs "Keep")))
      (when (buffer-live-p buffer)
        (with-current-buffer buffer (set-buffer-modified-p nil))
        (kill-buffer buffer)))))

(ert-deftest my/session-picker-orders-and-annotates ()
  (let ((tabs '((tab (group . "Old") (time . 10))
                (tab (group . "Recent") (time . 30)
                     (project-tab-sessions-root . "/tmp/project/"))
                (tab (group . "Recent") (time . 20))
                (current-tab (group . "Active")))))
    (cl-letf (((symbol-function 'tab-bar-tabs) (lambda (&optional _) tabs)))
      (should (equal (my/session-names) '("Active" "Recent" "Old")))
      (should (string-match-p "current.*1 tab" (my/session-annotation "Active")))
      (should (string-match-p "2 tabs.*\/tmp/project/" (my/session-annotation "Recent")))
      (should (string-match-p "no project" (my/session-annotation "Old")))
      (should (eq (completion-metadata-get
                   (completion-metadata "" #'my/session-completion-table nil)
                   'display-sort-function)
                  #'identity)))))

(ert-deftest my/session-picker-rename-preserves-project-and-selection ()
  (my/session-switch "Rename me")
  (tab-bar-new-tab)
  (tab-bar-change-tab-group "Rename me")
  (dolist (entry (project-tab-sessions--tabs "Rename me"))
    (project-tab-sessions--set-root (cdr entry) "/tmp/project/"))
  (let ((selected (tab-bar--current-tab-index)))
    (should-error (my/session-rename "Rename me" "Keep") :type 'user-error)
    (should-error (my/session-rename "Rename me" "  ") :type 'user-error)
    (my/session-rename "Rename me" "Renamed")
    (should (= selected (tab-bar--current-tab-index)))
    (should-not (project-tab-sessions--tabs "Rename me"))
    (should (= 2 (length (project-tab-sessions--tabs "Renamed"))))
    (dolist (entry (project-tab-sessions--tabs "Renamed"))
      (should (equal (alist-get 'project-tab-sessions-root (cdr entry)) "/tmp/project/"))
      (should (equal (alist-get 'project-tab-sessions-group (cdr entry)) "Renamed"))))
  (my/session-close "Renamed"))

(ert-deftest my/session-picker-directory-and-save-actions ()
  (let ((root (file-name-as-directory temporary-file-directory))
        opened saved)
    (my/session-switch "Project")
    (project-tab-sessions--set-root (tab-bar--current-tab-find) root)
    (my/session-switch "Keep")
    (cl-letf (((symbol-function 'dired) (lambda (directory) (setq opened directory)))
              ((symbol-function 'my/session-save) (lambda () (setq saved t))))
      (my/session-open-directory "Project")
      (should (equal opened root))
      (should (equal (alist-get 'group (tab-bar--current-tab-find)) "Project"))
      (my/session-save-desktop "Project")
      (should saved)
      (should-error (my/session-open-directory "Keep") :type 'user-error)
      (should-error (my/session-save-desktop "Missing") :type 'user-error))
    (my/session-close "Project")))

(ert-deftest my/session-picker-refresh-policy ()
  (dolist (action '(my/session-close my/session-rename my/session-save-desktop))
    (should (assq action embark-quit-after-action))
    (should-not (alist-get action embark-quit-after-action)))
  (dolist (action '(my/session-close my/session-rename))
    (should (memq #'embark--restart (alist-get action embark-post-action-hooks)))))

(setq kill-emacs-hook nil)
(ert-run-tests-batch-and-exit "my/session-picker-")
